apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
  name: ddc-argocd-demo
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: manojjahgirdar/ddc-argocd-demo:v6
        name: ddc-argocd-demo
